services:
  bundle-server:
    image: nginx:1.21
    container_name: bundle-server
    ports:
      - 1080:80
    volumes:
      - ./config/bundle-server/bundle.tar.gz:/usr/share/nginx/html/bundle.tar.gz
    networks:
      smo:

  opa-kafka:
    image: openpolicyagent/opa:latest-envoy
    container_name: opa-kafka
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "--set=services.authz.url=http://bundle-server"
      - "--set=bundles.authz.service=authz"
      - "--set=bundles.authz.resource=bundle.tar.gz"
    depends_on:
      - bundle-server
    networks:
      smo:

  identitydb:
    image: docker.io/bitnami/postgresql:13
    container_name: identitydb
    hostname: identitydb
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRESQL_PASSWORD=keycloak
    networks:
      smo:

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak
    command:
      - "start"
      - "--https-key-store-file=/etc/x509/https/keycloak.server.keystore.p12"
      - "--https-key-store-password=$${KC_KEYSTORE_PASSWORD}"
      - "--https-key-store-type=PKCS12"
      - "--https-trust-store-file=/etc/x509/https/keycloak.client.truststore.p12"
      - "--https-trust-store-password=$${KC_KEYSTORE_PASSWORD}"
      - "--https-trust-store-type=PKCS12"
      - "--https-client-auth=request"
      - "--http-enabled=true"
    ports:
      - 8462:8080
      - 8463:8443
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_KEYSTORE_PASSWORD=changeit
      - KC_HOSTNAME=keycloak
      - KC_HTTP_ENABLED=true
      - KEYCLOAK_DATABASE_HOST=identitydb
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak
      - KC_HTTPS_CLIENT_AUTH=request
    volumes:
      - ./config/keycloak/certs/keycloak.client.truststore.p12:/etc/x509/https/keycloak.client.truststore.p12
      - ./config/keycloak/certs/keycloak.server.keystore.p12:/etc/x509/https/keycloak.server.keystore.p12
    depends_on:
      identitydb:
        condition: service_started
    networks:
      smo:

networks:
  smo:
    external: true
